apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
# Helm Charts: https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows
- name: argo-workflows
  repo: https://argoproj.github.io/argo-helm
  version: 0.39.5
  releaseName: argo-workflows
  namespace: processing
  valuesFile: argo_workflows/argo_workflows.yaml

resources: []
