apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  # https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: "2.13.3"
    releaseName: sealed-secrets
    namespace: admin
    includeCRDs: true
    valuesFile: sealed-secrets.yaml

resources: []
