---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    server: https://kubernetes.default.svc
  project: crossplane
  source:
    path: argocd/kustomize/retail/crossplane/dev
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: argo-workflows
  source:
    path: argocd/kustomize/argo-workflows/overlays/dev
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: argo-events
  source:
    path: argocd/kustomize/argo-events/overlays/dev
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
