---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    server: https://kubernetes.default.svc
  project: crossplane
  source:
    path: argocd/kustomize/crossplane/overlays/dev
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: processing
    server: https://kubernetes.default.svc
  project: workflows
  source:
    path: argocd/kustomize/processing/overlays/dev
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: events
  source:
    path: argocd/kustomize/argo-events/overlays/dev
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
