apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-deployment-hpa
  namespace: admin
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 90
