apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
# Helm Charts: https://github.com/argoproj/argo-helm/tree/main/charts/argo-events
- name: argo-events
  repo: https://argoproj.github.io/argo-helm
  version: 2.4.1
  releaseName: argo-events
  namespace: argo-events
  valuesFile: argo_events/argo_events.yaml

resources: []
