apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
# Helm Charts: https://artifacthub.io/packages/helm/crossplane/crossplane
- name: argo-events
  repo: https://charts.crossplane.io/stable
  version: 1.14.3
  releaseName: crossplane
  namespace: crossplane

resources: []
