apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
# Helm Charts: https://artifacthub.io/packages/helm/crossplane/crossplane
- name: crossplane
  repo: https://charts.crossplane.io/stable
  # version: crossplane-1.14.3
  releaseName: crossplane
  namespace: crossplane

resources:
  - terraform_provider.yaml
