apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: web
  source:
    path: argocd/helm/webapp
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: helm
  source:
    path: argocd/manifests/apps
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: kustomize
  source:
    path: argocd/kustomize
    repoURL: https://github.com/mmochan/terraform-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
