apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading
  name: trading-deployment
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
  strategy: {}
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
        - image: nginx:latest
          name: trading
          resources: {}
