apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-cluster
  namespace: backstage
spec:
  instances: 3

  bootstrap:
    # initdb:
    #   database: backstage_plugin_catalog
    #   owner: backstage_plugin_catalog
    #   secret:
    #     name: backstage-db-secret

    initdb:
      database: app
      owner: app
      postInitSQL:
        - CREATE DATABASE backstage_plugin_catalog
        - CREATE DATABASE backstage_plugin_scaffolder
        - GRANT ALL PRIVILEGES ON DATABASE backstage_plugin_catalog TO app
        - GRANT ALL PRIVILEGES ON DATABASE backstage_plugin_scaffolder TO app
        - \c backstage_plugin_catalog postgres
        - GRANT ALL ON SCHEMA public TO app
        - \c backstage_plugin_scaffolder postgres
        - GRANT ALL ON SCHEMA public TO app
      # backstage_plugin_catalog:
      #   roles:
      #     - name: backstage_plugin_catalog
      #       password: "password1"
      #       options:
      #         - CREATEDB
      #         - CREATEROLE
      #     # - name: backstage_plugin_scaffolderer
      #     #   password: "password2"
      #     #   options:
      #     #     - CREATEDB
      #     #     - CREATEROLE

      # backstage_plugin_scaffolderer:
      #   roles:
      #     - name: backstage_plugin_scaffolderer
      #       password: "password2"
      #       options:
      #         - CREATEDB
      #         - CREATEROLE

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: false

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: backstage-db-secret
#   namespace: backstage
# data:
#   username: backstage
#   password: password
# type: kubernetes.io/basic-auth